name: Deploy and Preview on Pull Request

on:
  pull_request:
    types:
      - opened
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ECONIA_CI_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive

      - name: Deploy to Vercel
        uses: vercel/actions/deploy@v21
        # with:
        #   vercel-token: ${{ secrets.VERCEL_TOKEN }}
